### ISSUE TITLE
关于酷狗音乐逆向

### ISSUE THREAD

**Issue by mqk233** [xiayouran/Musicer#6]
最近在逆向酷狗apk，想实现登录之后使用会员token下载音乐，发现登陆参数差一个p2（也就是密码加密之后的256位字符串），这个参数貌似是调用libj.so库使用rsa之类加密的，这个大佬有研究过嘛，实在走不下去了，希望能提供一点思路。

**Comment by mqk233** [comment]
https://www.52pojie.cn/thread-1613545-1-1.html
详细过程在这个贴子里面，大佬有时间能帮忙看下嘛。

**Comment by xiayouran** [comment]
帖子写的不错:+1:，对于.so文件可以使用反汇编工具来查看原本的C/C++代码，比如主流的反汇编工具IDA Pro，当然在此基础之上还可以基于Frida-RPC、AndServer-RPC对.so文件进行模拟执行，可以基于这些思路来尝试一下

**Comment by mqk233** [comment]
> 

好的，ida感觉有点不会用，没学过汇编，难顶。
