### ISSUE TITLE
某狗 显示下载完毕 去文件夹看是空文件 0字节

### ISSUE THREAD

**Issue by kkxg** [xiayouran/Musicer#8]
能更新就好了。不更新也没事QAQ
帮我爸下歌 这首就不行。
黄建春 - 有啥不如有个好身体 (covr: 余晓清)(Live)
其他有的可以。

**Comment by kkxg** [comment]
去APP看了这首是会员期内有效歌曲。估计格式 不一样？没有这个限制的普通歌曲和会员过期也能听的歌曲是正常可以下载的。
![img](https://user-images.githubusercontent.com/20535377/193437683-9ff7e25e-995e-41ba-8597-07697f59204f.png)

**Comment by xiayouran** [comment]
@kkxg good boy👍，代码已经更新了，目前这首歌已经可以下载，麻烦拉取最新代码再次尝试，国庆快乐😆
